# Create secrets with actual values before applying
# Usage: kubectl apply -f backend-secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: mindx-secrets
type: Opaque
stringData:
  session-secret: "mindx-session-secret-prod-2025-az-k8s-secure"
  jwt-secret: "mindx-jwt-secret-prod-2025-kubernetes-token"
  openid-secret: "cHJdmVudGJvdWskYmFQdHJlZJlIZWV4GxvcmVjZWxsbVydm91c2ZhcG9ydiZhZhbnNOZWU="
  # Week 2: Azure Application Insights Connection String
  appinsights-connection-string: "InstrumentationKey=38d2b763-9213-4aeb-a74f-6fa4f6b39df8;IngestionEndpoint=https://southeastasia-1.in.applicationinsights.azure.com/;LiveEndpoint=https://southeastasia.livediagnostics.monitor.azure.com/;ApplicationId=0c19a94d-b9d1-4e7f-be63-065e312f31a1"
