# Create secrets with actual values before applying
# Usage: kubectl apply -f backend-secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: mindx-secrets
type: Opaque
stringData:
  session-secret: "mindx-session-secret-prod-2025-az-k8s-secure"
  jwt-secret: "mindx-jwt-secret-prod-2025-kubernetes-token"
  openid-secret: "cHJdmVudGJvdWskYmFQdHJlZJlIZWV4GxvcmVjZWxsbVydm91c2ZhcG9ydiZhZhbnNOZWU="
